In [4]:
from pathlib import Path

ruta = Path("../Datos/originales/mercados")

for elemento in ruta.rglob("*"):
    if elemento.is_file():
        print("Archivo:", elemento.relative_to(ruta))
    elif elemento.is_dir():
        print("Carpeta:", elemento.relative_to(ruta))

Archivo: datos.csv
Archivo: diccionario.csv
Carpeta: mercados_cdmx_sedeco
Archivo: mercados_cdmx_sedeco\MERCADOS_ADIP.cpg
Archivo: mercados_cdmx_sedeco\MERCADOS_ADIP.dbf
Archivo: mercados_cdmx_sedeco\MERCADOS_ADIP.prj
Archivo: mercados_cdmx_sedeco\MERCADOS_ADIP.sbn
Archivo: mercados_cdmx_sedeco\MERCADOS_ADIP.sbx
Archivo: mercados_cdmx_sedeco\MERCADOS_ADIP.shp
Archivo: mercados_cdmx_sedeco\MERCADOS_ADIP.shp.xml
Archivo: mercados_cdmx_sedeco\MERCADOS_ADIP.shx

In [5]:
import geopandas as gpd

ruta = "../Datos/originales/mercados/mercados_cdmx_sedeco/MERCADOS_ADIP.shp"

gdf_mercados = gpd.read_file(ruta)

print("Registros:", len(gdf_mercados))
print("Columnas:", gdf_mercados.columns.tolist())
print("Sistema de coordenadas:", gdf_mercados.crs)

display(gdf_mercados.head())

Registros: 329
Columnas: ['N°', 'DELEGACION', 'MERCADO', 'NUM_OFIC', 'NUM_LOCALE', 'Coord_Y', 'Coord_X', 'DIRECCION', 'COLONIA', 'TIPO', 'SUPERF_M2', 'INAUGURACI', 'ANTIGÜEDA', 'VOCACIÓN', 'DETALLE', 'FORMA', 'NIVELES', 'TAMAÑO1', 'PROTEGIDO', 'COORGEOG_X', 'COORGEOG_Y', 'geometry']
Sistema de coordenadas: EPSG:8992

c:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\pyogrio\raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured 3D Point' is converted to 'Point Z'
  return ogr_read(

,N°,DELEGACION,MERCADO,NUM_OFIC,NUM_LOCALE,Coord_Y,Coord_X,DIRECCION,COLONIA,TIPO,...,ANTIGÜEDA,VOCACIÓN,DETALLE,FORMA,NIVELES,TAMAÑO1,PROTEGIDO,COORGEOG_X,COORGEOG_Y,geometry
0,18.0,AZCAPOTZALCO,AZCAPOTZALCO,35.0,546.0,2.154268e+06,480539.52674,AV. AZCAPOTZALCO ENTRE ESPERANZA Y RAYON,AZCAPOTZALCO,TRADICIONAL,...,63.0,N/D,N/D,CUADRO,1,MEDIANO,SI,-99.185439,19.482872,POINT Z (-99.18544 19.48287 0)
1,20.0,AZCAPOTZALCO,CLAVERIA,46.0,98.0,2.152290e+06,480987.33324,IRAPUATO Y CLAVERIA S/N,CLAVERIA,TRADICIONAL,...,73.0,N/D,N/D,CUADRO,1,CHICO,NO,-99.181152,19.465003,POINT Z (-99.18115 19.465 0)
2,17.0,AZCAPOTZALCO,ARENAL,125.0,198.0,2.152428e+06,484181.95416,ALAMO Y CALLE 6 ENTRE OLIVO Y CALLE 6,ARENAL,TRADICIONAL,...,57.0,N/D,N/D,RECTANGULO,1,CHICO,SI,-99.150715,19.466271,POINT Z (-99.15071 19.46627 0)
3,29.0,AZCAPOTZALCO,PROHOGAR,126.0,641.0,2.153488e+06,483884.41298,CALLE 14 S/N ENTRE CALLES 19 Y 21,PROHOGAR,TRADICIONAL,...,57.0,"ROPA, CALZADO Y TELAS",ROPA,CUADRO,1,GRANDE,NO,-99.153559,19.475848,POINT Z (-99.15356 19.47585 0)
4,33.0,AZCAPOTZALCO,SANTA LUCIA,137.0,150.0,2.153555e+06,479388.53462,AV. SANTA LUCIA ENTRE CENTEOTL Y ACATL,SANTA LUCIA,TRADICIONAL,...,56.0,N/D,N/D,CUADRO,1,CHICO,NO,-99.196399,19.476417,POINT Z (-99.1964 19.47642 0)

In [6]:
# Valores faltantes
print("VALORES FALTANTES")
print(gdf_mercados.isna().sum())

# Duplicados exactos
print("\nDUPLICADOS EXACTOS")
print(gdf_mercados.duplicated().sum())

# Nombres de mercados repetidos
print("\nNOMBRES REPETIDOS")
print(gdf_mercados["MERCADO"].value_counts().head(15))

# Mercados por alcaldía
print("\nMERCADOS POR ALCALDÍA")
print(gdf_mercados["DELEGACION"].value_counts())

# Tipos de mercado
print("\nTIPOS")
print(gdf_mercados["TIPO"].value_counts(dropna=False))

VALORES FALTANTES
N°            0
DELEGACION    0
MERCADO       0
NUM_OFIC      0
NUM_LOCALE    0
Coord_Y       0
Coord_X       0
DIRECCION     0
COLONIA       0
TIPO          0
SUPERF_M2     0
INAUGURACI    0
ANTIGÜEDA     0
VOCACIÓN      0
DETALLE       0
FORMA         0
NIVELES       0
TAMAÑO1       0
PROTEGIDO     0
COORGEOG_X    0
COORGEOG_Y    0
geometry      0
dtype: int64

DUPLICADOS EXACTOS
0

NOMBRES REPETIDOS
MERCADO
PROVIDENCIA                    2
EMILIANO ZAPATA                2
MIGUEL HIDALGO                 2
VEINTICUATRO DE FEBRERO        2
AZCAPOTZALCO                   1
CLAVERIA                       1
ARENAL                         1
PROHOGAR                       1
SANTA LUCIA                    1
COSMOPOLITA                    1
VICTORIA DE LAS DEMOCRACIAS    1
OBRERO POPULAR                 1
NUEVA SANTA MARIA              1
BENITO JUAREZ                  1
TLATILCO                       1
Name: count, dtype: int64

MERCADOS POR ALCALDÍA
DELEGACION
GUSTAVO A. MADERO      51
VENUSTIANO CARRANZA    42
CUAUHTÉMOC             39
COYOACÁN               22
IZTAPALAPA             20
TLALPAN                20
AZCAPOTZALCO           19
MIGUEL HIDALGO         19
TLÁHUAC                18
IZTACALCO              16
ÁLVARO OBREGÓN         16
BENITO JUÁREZ          16
XOCHIMILCO             11
MILPA ALTA             10
CUAJIMALPA              5
MAGDALENA CONTRERAS     5
Name: count, dtype: int64

TIPOS
TIPO
TRADICIONAL                  276
ESPECIALIZADO                 44
TURISTICO Y ESPECIALIZADO      7
TRADICIONAL Y TURISTICO        2
Name: count, dtype: int64

In [7]:
print("COORDENADAS FALTANTES")
print(gdf_mercados[["COORGEOG_X", "COORGEOG_Y"]].isna().sum())

print("\nRANGOS GEOGRÁFICOS")
print(gdf_mercados[["COORGEOG_X", "COORGEOG_Y"]].describe())

print("\nGEOMETRÍAS VACÍAS")
print(gdf_mercados.geometry.is_empty.sum())

print("\nGEOMETRÍAS NULAS")
print(gdf_mercados.geometry.isna().sum())

print("\nTIPOS DE GEOMETRÍA")
print(gdf_mercados.geometry.geom_type.value_counts())

COORDENADAS FALTANTES
COORGEOG_X    0
COORGEOG_Y    0
dtype: int64

RANGOS GEOGRÁFICOS
       COORGEOG_X  COORGEOG_Y
count  329.000000  329.000000
mean   -99.129478   19.390182
std      0.059035    0.077338
min    -99.300662   19.176109
25%    -99.165484   19.337333
50%    -99.127952   19.407471
75%    -99.094934   19.450055
max    -98.961816   19.549417

GEOMETRÍAS VACÍAS
0

GEOMETRÍAS NULAS
0

TIPOS DE GEOMETRÍA
Point    329
Name: count, dtype: int64

In [8]:
# Revisar identificadores repetidos
print("NUM_OFIC duplicados:")
print(gdf_mercados["NUM_OFIC"].duplicated().sum())

# Revisar posibles ubicaciones repetidas
print("\nCoordenadas repetidas:")
print(
    gdf_mercados.duplicated(
        subset=["COORGEOG_X", "COORGEOG_Y"]
    ).sum()
)

# Comparar coordenadas con geometría
diferencia_x = (
    gdf_mercados.geometry.x -
    gdf_mercados["COORGEOG_X"]
).abs()

diferencia_y = (
    gdf_mercados.geometry.y -
    gdf_mercados["COORGEOG_Y"]
).abs()

print("\nDiferencia máxima en longitud:", diferencia_x.max())
print("Diferencia máxima en latitud:", diferencia_y.max())

# Revisar valores N/D
print("\nValores N/D por columna:")
print(gdf_mercados.astype(str).eq("N/D").sum())

NUM_OFIC duplicados:
2

Coordenadas repetidas:
2

Diferencia máxima en longitud: 0.11154299990532479
Diferencia máxima en latitud: 0.12133699964429923

Valores N/D por columna:
N°              0
DELEGACION      0
MERCADO         0
NUM_OFIC        0
NUM_LOCALE      0
Coord_Y         0
Coord_X         0
DIRECCION       0
COLONIA         0
TIPO            0
SUPERF_M2       0
INAUGURACI      0
ANTIGÜEDA       0
VOCACIÓN      241
DETALLE       242
FORMA           0
NIVELES         0
TAMAÑO1         0
PROTEGIDO       0
COORGEOG_X      0
COORGEOG_Y      0
geometry        0
dtype: int64

In [9]:
# Copia para realizar las verificaciones
revision = gdf_mercados.copy()

# Diferencias entre geometría y coordenadas
revision["dif_lon"] = (
    revision.geometry.x - revision["COORGEOG_X"]
).abs()

revision["dif_lat"] = (
    revision.geometry.y - revision["COORGEOG_Y"]
).abs()

# Mercados con diferencias importantes
problemas_geo = revision[
    (revision["dif_lon"] > 0.001) |
    (revision["dif_lat"] > 0.001)
]

print("MERCADOS CON DIFERENCIAS GEOGRÁFICAS")
print("Total:", len(problemas_geo))

display(
    problemas_geo[
        ["DELEGACION", "MERCADO", "DIRECCION",
         "COORGEOG_X", "COORGEOG_Y", "dif_lon", "dif_lat"]
    ]
)

# Identificadores oficiales repetidos
print("\nIDENTIFICADORES REPETIDOS")

display(
    revision[
        revision.duplicated("NUM_OFIC", keep=False)
    ][["DELEGACION", "MERCADO", "NUM_OFIC", "DIRECCION"]]
)

# Coordenadas repetidas
print("\nCOORDENADAS REPETIDAS")

display(
    revision[
        revision.duplicated(
            ["COORGEOG_X", "COORGEOG_Y"],
            keep=False
        )
    ][["DELEGACION", "MERCADO", "DIRECCION",
       "COORGEOG_X", "COORGEOG_Y"]]
)

MERCADOS CON DIFERENCIAS GEOGRÁFICAS
Total: 2

,DELEGACION,MERCADO,DIRECCION,COORGEOG_X,COORGEOG_Y,dif_lon,dif_lat
54,GUSTAVO A. MADERO,TRES ESTRELLAS,"MARTIRES IRLANDESES, ENTRE JUAN AGUILAR Y LOPE...",-99.147062,19.349777,0.035984,0.121337
266,MIGUEL HIDALGO,DIECIOCHO DE MARZO,"CALLE 69 Y AV. 4, ENTRE 65 Y 67",-99.082984,19.410297,0.111543,0.036946

IDENTIFICADORES REPETIDOS

,DELEGACION,MERCADO,NUM_OFIC,DIRECCION
23,COYOACÁN,CHURUBUSCO,171.0,"MARTIRES IRLANDESES, ENTRE JUAN AGUILAR Y LOPE..."
54,GUSTAVO A. MADERO,TRES ESTRELLAS,171.0,"MARTIRES IRLANDESES, ENTRE JUAN AGUILAR Y LOPE..."
266,MIGUEL HIDALGO,DIECIOCHO DE MARZO,85.0,"CALLE 69 Y AV. 4, ENTRE 65 Y 67"
284,VENUSTIANO CARRANZA,PUEBLA,85.0,"CALLE 69 Y AV. 4, ENTRE 65 Y 67"

COORDENADAS REPETIDAS

,DELEGACION,MERCADO,DIRECCION,COORGEOG_X,COORGEOG_Y
23,COYOACÁN,CHURUBUSCO,"MARTIRES IRLANDESES, ENTRE JUAN AGUILAR Y LOPE...",-99.147062,19.349777
54,GUSTAVO A. MADERO,TRES ESTRELLAS,"MARTIRES IRLANDESES, ENTRE JUAN AGUILAR Y LOPE...",-99.147062,19.349777
266,MIGUEL HIDALGO,DIECIOCHO DE MARZO,"CALLE 69 Y AV. 4, ENTRE 65 Y 67",-99.082984,19.410297
284,VENUSTIANO CARRANZA,PUEBLA,"CALLE 69 Y AV. 4, ENTRE 65 Y 67",-99.082984,19.410297

In [10]:
# Registros que presentan inconsistencias
indices = [23, 54, 266, 284]

comparacion = gdf_mercados.loc[indices].copy()

# Coordenadas provenientes de la geometría
comparacion["lon_geometry"] = comparacion.geometry.x
comparacion["lat_geometry"] = comparacion.geometry.y

columnas = [
    "DELEGACION",
    "MERCADO",
    "NUM_OFIC",
    "DIRECCION",
    "COLONIA",
    "COORGEOG_X",
    "COORGEOG_Y",
    "lon_geometry",
    "lat_geometry"
]

display(comparacion[columnas])

,DELEGACION,MERCADO,NUM_OFIC,DIRECCION,COLONIA,COORGEOG_X,COORGEOG_Y,lon_geometry,lat_geometry
23,COYOACÁN,CHURUBUSCO,171.0,"MARTIRES IRLANDESES, ENTRE JUAN AGUILAR Y LOPE...",HEROES DEL 47,-99.147062,19.349777,-99.147062,19.349777
54,GUSTAVO A. MADERO,TRES ESTRELLAS,171.0,"MARTIRES IRLANDESES, ENTRE JUAN AGUILAR Y LOPE...",HEROES DEL 47,-99.147062,19.349777,-99.111078,19.471114
266,MIGUEL HIDALGO,DIECIOCHO DE MARZO,85.0,"CALLE 69 Y AV. 4, ENTRE 65 Y 67",PUEBLA,-99.082984,19.410297,-99.194527,19.447243
284,VENUSTIANO CARRANZA,PUEBLA,85.0,"CALLE 69 Y AV. 4, ENTRE 65 Y 67",PUEBLA,-99.082984,19.410297,-99.082984,19.410297

In [11]:
import pandas as pd

# Copiar la base original
gdf_mercados_final = gdf_mercados.copy()

# Guardar coordenadas originales de los atributos
gdf_mercados_final["longitud_original"] = gdf_mercados_final["COORGEOG_X"]
gdf_mercados_final["latitud_original"] = gdf_mercados_final["COORGEOG_Y"]

# Extraer coordenadas de la geometría
gdf_mercados_final["longitud"] = gdf_mercados_final.geometry.x
gdf_mercados_final["latitud"] = gdf_mercados_final.geometry.y

# Identificar discrepancias
gdf_mercados_final["revision_pendiente"] = (
    (gdf_mercados_final["longitud"] -
     gdf_mercados_final["longitud_original"]).abs() > 0.001
) | (
    (gdf_mercados_final["latitud"] -
     gdf_mercados_final["latitud_original"]).abs() > 0.001
)

# Convertir N/D en valores nulos
gdf_mercados_final = gdf_mercados_final.replace("N/D", pd.NA)

print("Mercados:", len(gdf_mercados_final))
print("Pendientes de revisión:", gdf_mercados_final["revision_pendiente"].sum())

Mercados: 329
Pendientes de revisión: 2

In [12]:
from pathlib import Path

ruta_salida = Path("../Datos/procesados")
ruta_salida.mkdir(parents=True, exist_ok=True)

# CSV sin la columna geométrica
gdf_mercados_final.drop(columns="geometry").to_csv(
    ruta_salida / "mercados_cdmx_sedeco.csv",
    index=False,
    encoding="utf-8-sig"
)

# GeoParquet con la geometría
gdf_mercados_final.to_parquet(
    ruta_salida / "mercados_cdmx_sedeco.parquet",
    index=False
)

print("Archivos guardados correctamente")

Archivos guardados correctamente